version: '3'
services:
  discord-bot:
    build: 
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    command: npm run build && npm start