version: '3'
services:
  discord-bot:
    build: .
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data/postgres: